/*
Problem: Spiral Matrix II

Approach:
Use boundary pointers to fill the matrix in spiral order.

1. Create an n × n matrix.
2. Maintain four boundaries:
   - top
   - bottom
   - left
   - right
3. Fill the matrix layer by layer in four directions:
   - left → right
   - top → bottom
   - right → left
   - bottom → top
4. After each traversal, move the corresponding boundary inward.
5. Continue until all cells are filled.

Simulation Idea:
The spiral pattern is generated by shrinking the
matrix boundaries after completing one full layer traversal.

Time Complexity: O(n²)
Space Complexity: O(1) (excluding output matrix)
*/

class Solution {
    public int[][] generateMatrix(int n) {

        int[][] matrix = new int[n][n];

        int top = 0;
        int bottom = matrix.length - 1;

        int left = 0;
        int right = matrix[0].length - 1;
        int add = 1;

        while(top <= bottom && left <= right)
        {
            //left to right
            for(int i = left ; i <= right ; i++)
            {
                matrix[top][i] = add++;
            }
            top++;

            //top to bottom
            if(top <= bottom && left <= right)
            {
                for(int i = top ; i <= bottom ; i++)
                {
                   matrix[i][right] = add++;
                }
            }
            right--;
            
            //right to left
            if(top <= bottom && left <= right)
            {
                for(int i = right ; i >= left ; i--)
                {
                    matrix[bottom][i] = add++;
                }
            }
            bottom--;

            //bottom to top
            if(top <= bottom && left <= right)
            {
                for(int i = bottom ; i >= top ; i--)
                {
                    matrix[i][left] = add++;
                }
            }
            left++;
    

        }  
        return matrix;  

    }
}
